plots: 0
exp_name: seed_2
seed: 2
# outf: /Users/mariana/Documents/projects/Graphs/EGNN_VAE/nodes_100_community
outf: /home/mvargas/code/Graphs/EGNN_VAE/nodes_20_community/base_dim3/

train:
  epochs: 150
  no-cuda: 0
  log_interval: 100
  test_interval: 2
  generate-interval: 100
  lr: 1e-4

data:
  dataset: community_ours
  with_pos: 0
  n_nodes: 20
  
model:
  model: ae_egnn
  nf: 64
  emb_nf: 8
  K: 3
  attention: 0
  noise_dim: 0
  n_layers: 4
  reg: 1e-3
  clamp: 1
  weight_decay: 1e-16
  
